export const LOCAL_VOCABULARY = {
	i: {
		kanji: "私",
		kana: "わたし",
		type: "noun",
		difficulty: "easy",
		roles: ["subject"],
		english: { subject: "I", object: "me" },
		thirdPersonSingular: false,
	},
	he: {
		kanji: "彼",
		kana: "かれ",
		type: "noun",
		difficulty: "easy",
		roles: ["subject", "patient"],
		english: { subject: "he", object: "him" },
		thirdPersonSingular: true,
	},
	she: {
		kanji: "彼女",
		kana: "かのじょ",
		type: "noun",
		difficulty: "easy",
		roles: ["subject", "patient"],
		english: { subject: "she", object: "her" },
		thirdPersonSingular: true,
	},
	teacher: {
		kanji: "先生",
		kana: "せんせい",
		type: "noun",
		difficulty: "easy",
		roles: ["subject", "agent", "companion"],
		english: { subject: "the teacher", object: "the teacher" },
		thirdPersonSingular: true,
	},
	student: {
		kanji: "学生",
		kana: "がくせい",
		type: "noun",
		difficulty: "medium",
		roles: ["subject", "patient", "agent", "companion"],
		english: { subject: "the student", object: "the student" },
		thirdPersonSingular: true,
	},
	friend: {
		kanji: "友達",
		kana: "ともだち",
		type: "noun",
		difficulty: "medium",
		roles: ["subject", "patient", "agent", "companion"],
		english: { subject: "my friend", object: "my friend" },
		thirdPersonSingular: true,
	},
	school: {
		kanji: "学校",
		kana: "がっこう",
		type: "noun",
		difficulty: "easy",
		roles: ["place", "destination"],
		english: { place: "at school", destination: "to school" },
	},
	station: {
		kanji: "駅",
		kana: "えき",
		type: "noun",
		difficulty: "easy",
		roles: ["place", "destination"],
		english: { place: "at the station", destination: "to the station" },
	},
	library: {
		kanji: "図書館",
		kana: "としょかん",
		type: "noun",
		difficulty: "easy",
		roles: ["place", "destination"],
		english: { place: "at the library", destination: "to the library" },
	},
	home: {
		kanji: "家",
		kana: "いえ",
		type: "noun",
		difficulty: "easy",
		roles: ["place", "destination"],
		english: { place: "at home", destination: "home" },
	},
	room: {
		kanji: "部屋",
		kana: "へや",
		type: "noun",
		difficulty: "medium",
		roles: ["place", "destination"],
		english: { place: "in the room", destination: "to the room" },
	},
	store: {
		kanji: "店",
		kana: "みせ",
		type: "noun",
		difficulty: "medium",
		roles: ["place", "destination"],
		english: { place: "at the store", destination: "to the store" },
	},
	park: {
		kanji: "公園",
		kana: "こうえん",
		type: "noun",
		difficulty: "medium",
		roles: ["place", "destination"],
		english: { place: "at the park", destination: "to the park" },
	},
	company: {
		kanji: "会社",
		kana: "かいしゃ",
		type: "noun",
		difficulty: "medium",
		roles: ["place", "destination"],
		english: { place: "at the company", destination: "to the company" },
	},
	hospital: {
		kanji: "病院",
		kana: "びょういん",
		type: "noun",
		difficulty: "medium",
		roles: ["place", "destination"],
		english: { place: "at the hospital", destination: "to the hospital" },
	},
	movieTheater: {
		kanji: "映画館",
		kana: "えいがかん",
		type: "noun",
		difficulty: "medium",
		roles: ["place", "destination"],
		english: { place: "at the movie theater", destination: "to the movie theater" },
	},
	rain: {
		kanji: "雨",
		kana: "あめ",
		type: "noun",
		difficulty: "easy",
		roles: ["weather"],
		english: { subject: "it" },
		thirdPersonSingular: true,
	},
	book: {
		kanji: "本",
		kana: "ほん",
		type: "noun",
		difficulty: "easy",
		roles: ["object"],
		english: { object: "a book" },
	},
	sushi: {
		kanji: "寿司",
		kana: "すし",
		type: "noun",
		difficulty: "easy",
		roles: ["object"],
		english: { object: "sushi" },
	},
	water: {
		kanji: "水",
		kana: "みず",
		type: "noun",
		difficulty: "easy",
		roles: ["object"],
		english: { object: "water" },
	},
	japanese: {
		kanji: "日本語",
		kana: "にほんご",
		type: "noun",
		difficulty: "easy",
		roles: ["object"],
		english: { object: "Japanese" },
	},
	movie: {
		kanji: "映画",
		kana: "えいが",
		type: "noun",
		difficulty: "medium",
		roles: ["object"],
		english: { object: "a movie" },
	},
	letter: {
		kanji: "手紙",
		kana: "てがみ",
		type: "noun",
		difficulty: "medium",
		roles: ["object"],
		english: { object: "a letter" },
	},
	newspaper: {
		kanji: "新聞",
		kana: "しんぶん",
		type: "noun",
		difficulty: "medium",
		roles: ["object"],
		english: { object: "the newspaper" },
	},
	rice: {
		kanji: "ご飯",
		kana: "ごはん",
		type: "noun",
		difficulty: "medium",
		roles: ["object"],
		english: { object: "rice" },
	},
	tea: {
		kanji: "お茶",
		kana: "おちゃ",
		type: "noun",
		difficulty: "medium",
		roles: ["object"],
		english: { object: "tea" },
	},
	music: {
		kanji: "音楽",
		kana: "おんがく",
		type: "noun",
		difficulty: "medium",
		roles: ["object"],
		english: { object: "music" },
	},
	go: {
		kanji: "行く",
		kana: "いく",
		type: "verb",
		difficulty: "easy",
		roles: ["verb"],
		english: { base: "go", present3: "goes", past: "went" },
	},
	come: {
		kanji: "くる",
		kana: "くる",
		type: "verb",
		difficulty: "medium",
		roles: ["verb"],
		english: { base: "come", present3: "comes", past: "came" },
	},
	eat: {
		kanji: "食べる",
		kana: "たべる",
		type: "verb",
		difficulty: "easy",
		roles: ["verb"],
		english: { base: "eat", present3: "eats", past: "ate" },
	},
	drink: {
		kanji: "飲む",
		kana: "のむ",
		type: "verb",
		difficulty: "easy",
		roles: ["verb"],
		english: { base: "drink", present3: "drinks", past: "drank" },
	},
	read: {
		kanji: "読む",
		kana: "よむ",
		type: "verb",
		difficulty: "easy",
		roles: ["verb"],
		english: { base: "read", present3: "reads", past: "read" },
	},
	buy: {
		kanji: "買う",
		kana: "かう",
		type: "verb",
		difficulty: "medium",
		roles: ["verb"],
		english: { base: "buy", present3: "buys", past: "bought" },
	},
	study: {
		kanji: "勉強する",
		kana: "べんきょうする",
		type: "verb",
		difficulty: "easy",
		roles: ["verb"],
		english: { base: "study", present3: "studies", past: "studied" },
	},
	watch: {
		kanji: "見る",
		kana: "みる",
		type: "verb",
		difficulty: "medium",
		roles: ["verb"],
		english: { base: "watch", present3: "watches", past: "watched" },
	},
	write: {
		kanji: "書く",
		kana: "かく",
		type: "verb",
		difficulty: "medium",
		roles: ["verb"],
		english: { base: "write", present3: "writes", past: "wrote" },
	},
	speak: {
		kanji: "話す",
		kana: "はなす",
		type: "verb",
		difficulty: "medium",
		roles: ["verb"],
		english: { base: "speak", present3: "speaks", past: "spoke" },
	},
	wait: {
		kanji: "待つ",
		kana: "まつ",
		type: "verb",
		difficulty: "medium",
		roles: ["verb"],
		english: { base: "wait", present3: "waits", past: "waited" },
	},
	use: {
		kanji: "使う",
		kana: "つかう",
		type: "verb",
		difficulty: "medium",
		roles: ["verb"],
		english: { base: "use", present3: "uses", past: "used" },
	},
	make: {
		kanji: "作る",
		kana: "つくる",
		type: "verb",
		difficulty: "medium",
		roles: ["verb"],
		english: { base: "make", present3: "makes", past: "made" },
	},
	praise: {
		kanji: "褒める",
		kana: "ほめる",
		type: "verb",
		difficulty: "medium",
		roles: ["verb"],
		english: { base: "praise", present3: "praises", past: "praised" },
	},
	fall: {
		kanji: "降る",
		kana: "ふる",
		type: "verb",
		difficulty: "easy",
		roles: ["verb"],
		english: { base: "rain", present3: "rains", past: "rained" },
	},
}

export function getLocalVocabularyWord(key) {
	const word = LOCAL_VOCABULARY[key]
	if (!word) throw new Error(`Unknown local prompt word: ${key}`)

	return word
}
